version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
      - http.cors.enabled=true
      - http.cors.allow-origin=http://10.0.230.100:8080
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 20s
      timeout: 20s
      retries: 3

  elasticvue:
    image: cars10/elasticvue
    container_name: elasticvue
    ports:
      - 8080:8080

  fscrawler:
    image: dadoonet/fscrawler
    container_name: fscrawler
    restart: always
    volumes:
      - ./config:/root/.fscrawler
      - ./logs:/usr/share/fscrawler/logs
      - ./data:/tmp/es:ro
    depends_on:
      elasticsearch:
        condition: service_healthy
    command: fscrawler --restart idx

volumes:
  data:
    driver: local
